sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t metafield/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true metafield/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "doicker-react"
  env: "DoickerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-496140043029"
  bucket_path: "doicker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY